spring:
  datasource:
    url: jdbc:mysql://rm-bp19voh3j79q52965mo.mysql.rds.aliyuncs.com:3306/work?useSSL=true&autoReconnect=true
    username: lp
    password: Work123456
    driver-class-name: com.mysql.jdbc.Driver

  mail:
    host: smtp.qq.com
    username: 574159150@qq.com
    password: pyvpapmfzdilbeib
    default-encoding: UTF-8
    port: 465
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.debug: true

  thymeleaf:
      encoding: utf-8
      #开发时关闭缓存，不然无法看到实时页面
      cache: false
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
  redis:
      # Redis数据库索引（默认为 0）
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis 密码
      password:
      jedis:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 8
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 2000
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 10000
      # 连接超时时间（毫秒）
      timeout: 0
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  returnPageInfo: check
shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 1800
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认86400秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /css/**,/js/**,/fonts/**,/img/**,/regist,/gifCode,/
    # 登录 url
    loginUrl: /login
    # 登录成功后跳转的 url
    successUrl: /index
    # 登出 url
    logoutUrl: /logout
    # 未授权跳转 url
    unauthorizedUrl: /403

elasticsearch:
  es_ip: 127.0.0.1
  es_port: 9200
mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.jingxiang.datachange.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null

mapper:
  mappers: com.jingxiang.datachange.config.MyMapper
  not-empty: false
  identity: MYSQL
server:
  port: 7000
  tomcat:
    uri-encoding: utf-8
oauth:
  qq:
    #你的appid
    client_id: 123456
    #你的appkey
    client_secret: aaaaaaaaaaaa
    #你接收响应code码地址,回调地址
    redirect_uri: http://localhost:7000/authorize/qq
    #腾讯获取code码地址
    code_callback_uri: https://graph.qq.com/oauth2.0/authorize
    #腾讯获取access_token地址
    access_token_callback_uri: https://graph.qq.com/oauth2.0/token
    #腾讯获取openid地址
    openid_callback_uri: https://graph.qq.com/oauth2.0/me
    #腾讯获取用户信息地址
    user_info_callback_uri: https://graph.qq.com/user/get_user_info
